### ISSUE TITLE
a compilation error when using the llvm in VS2022

### ISSUE THREAD

**Issue by icyfox168168** [Chemiculs/qengine#8]
1>C:\Users\HUAWEI\Desktop\qengine\src\qengine/engine/hashtypes/../../qhash/qhash.hpp(286,22): error : unknown type name 'byte'; did you mean 'std::byte'?

**Comment by Chemiculs** [comment]
thank you for bringing this issue to my attention - i just pushed an update to the main branch which resolves this issue.

**Comment by icyfox168168** [comment]
A new compilation problem has occurred

1>C:\Users\HUAWEI\Desktop\qengine\src\qengine/engine/hashtypes/qtype_hash.hpp(169,17): error : use of undeclared identifier 'qhash'
1>C:\Users\HUAWEI\Desktop\qengine\src\qengine/engine/hashtypes/qtype_hash.hpp(182,18): error : use of undeclared identifier 'qhash'

**Comment by Chemiculs** [comment]
I looked into your issue, and i believe the only possible cause would be a namespace addressing problem probably created by my local setup.

The newest push uses full namespace addressing and should resolve this problem. apologies on the late response, i have been busy moving homes.

**Comment by Chemiculs** [comment]
I greatly appreciate you bringing these bugs to my attention above all else !

I will close this ticket for now, if another issue occurs feel free to open another and / or contact me through Discord.
